Bricktheworld/develop
BlueBubblesApp/BlueBubbles-Android-App pull request #605
Opened 2020-12-30 20:17 UTC by SoPat712

This PR removes unused imports, makes it possible to pin conversations on selection, makes all back buttons on material Icons.Arrow_back instead of icons.arrow_back_ios, and also changes the "You have no chats" text to "You have no archived chats". It also changes the color of the settings icon on Material to be white instead of grey.

2020-12-30 22:10 UTC, zlshames commented
I changed the branch this was merging into. Please use `zach/nightly` from now on since Brandon isn't here anymore.

2020-12-30 22:41 UTC, SoPat712 commented
alright, so should I rewrite this pr into zach/nightly?

2020-12-30 22:45 UTC, zlshames requested changes
Please see my comments to improve the PR

2020-12-30 22:45 UTC, zlshames commented on ios/Flutter/Debug.xcconfig
> +#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
These changes need to be removed from the PR

2020-12-30 22:45 UTC, zlshames commented on ios/Flutter/Release.xcconfig
> +#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
These changes need to be removed from the PR

2020-12-30 22:45 UTC, zlshames commented on ios/Podfile
> +# Uncomment this line to define a global platform for your project
These changes need to be removed from the PR

2020-12-30 22:45 UTC, zlshames commented on lib/layouts/conversation_view/new_chat_creator/contact_selector_custom_cupertino_textfield.dart
> -          onContentCommited: widget.onContentCommited,
You need to revert these changes in the PR

2020-12-30 22:45 UTC, zlshames commented on lib/layouts/conversation_view/text_field/blue_bubbles_text_field.dart
> -                  onContentCommited: onContentCommit,
Please revert these changes for the PR

2020-12-30 22:45 UTC, zlshames commented on lib/layouts/conversation_view/text_field/blue_bubbles_text_field.dart
> -                  onContentCommited: onContentCommit,
Please revert these changes for the PR

2020-12-30 22:45 UTC, zlshames commented on lib/layouts/widgets/CustomCupertinoTextField.dart
> -          onContentCommited: widget.onContentCommited,
Please revert these changes for the PR

2020-12-30 22:45 UTC, zlshames commented on packages/extended_text_field/pubspec.lock
>        name: async
Please revert these changes for the PR

2020-12-30 22:45 UTC, zlshames commented on packages/extended_text_field/pubspec.lock
>        name: source_span
Please revert these changes for the PR

2020-12-30 22:45 UTC, zlshames commented on packages/gif_text_field/pubspec.lock
> +    version: "2.5.0-nullsafety.1"
Please revert these changes for the PR

2020-12-30 22:49 UTC, zlshames commented
> alright, so should I rewrite this pr into zach/nightly?

Nope, I changed it for you. Just address the comments above and you'll be golden

2020-12-30 22:59 UTC, SoPat712 commented
think I just fixed them with [this commit](https://github.com/BlueBubblesApp/BlueBubbles-Android-App/pull/605/commits/8c8bbd9534aba2b025a220b5b6df7a72bde4168a)

2020-12-30 23:02 UTC, SoPat712 reviewed
Fixed?

2020-12-30 23:02 UTC, SoPat712 commented
IDK how this works sorry for bugging so much.

2020-12-30 23:19 UTC, zlshames commented
Err, so you made a commit, but it was just new code. It wasn't fixing the comments i made.

2020-12-30 23:24 UTC, zlshames commented
I think you fixed some of the issues, but not all. For instance, the pubspec.lock stuff

2020-12-31 20:19 UTC, SoPat712 commented
I think I just fixed everything, can you please review it again? I removed all the files that weren't specifically changes I made, I think.

2021-01-03 17:08 UTC, zlshames approved these changes
Close Enough

2021-01-03 17:09 UTC, merged

2021-01-03 17:34 UTC, SoPat712 commented
Lmao