Add support for .heic images in fullscreen mode and show a proper error when the image fails to load
BlueBubblesApp/BlueBubbles-Android-App pull request #915
Opened 2021-06-22 22:37 UTC by tneotia

Fixes #911.

Not the best solution because .heic will still appear slightly compressed in the fullscreen viewer but its better than not being able to see the image at all.

2021-06-22 23:11 UTC, jjoelj requested changes
* Change error text to "Failed to display image" rather than "Failed to load image"
* Use an if-else in `initBytes()` Don't need to use flutter's `readAsBytes()` for no reason
* make the text style of the error widget theme-reliant using a property of `Theme.of(context)`

2021-06-22 23:22 UTC, tneotia commented
> * make the text style of the error widget theme-reliant using a property of `Theme.of(context)`

@jjoelj for that last one the viewer is black in light mode too so we don't want black text on black BG using `Theme.of(context)`. Is there some other property that I can use? 

Technically I could check if the color is black and correct it but it's not ideal.

2021-06-22 23:31 UTC, jjoelj approved these changes
> > * make the text style of the error widget theme-reliant using a property of `Theme.of(context)`
> 
> @jjoelj for that last one the viewer is black in light mode too so we don't want black text on black BG using `Theme.of(context)`. Is there some other property that I can use?
> 
> Technically I could check if the color is black and correct it but it's not ideal.

Now that I look at the existing code, it looks like a lot of the colors are hardcoded. In that case this looks good. We can open a separate ticket for making the photoviewer as a whole more responsive to the theme.

2021-06-23 01:31 UTC, zlshames approved these changes
Agreed, not a long term solution, but a step in the right direction

2021-06-23 01:32 UTC, zlshames commented on lib/layouts/image_viewer/image_viewer.dart
> +                      loadFailedChild: Center(
Before I merge this, can you share what this widget will look like? Is it consistent with what we have in other areas?

2021-06-23 01:48 UTC, merged

2021-06-23 01:50 UTC, zlshames commented
There is another ticket regarding .heic support. Since this is not a full solution, I am leaving that one open